skip-check:
  - CKV_AZURE_109 # Key vault firewall rules.
  - CKV_AZURE_112 # Key vault key is backed by HSM.
  - CKV_AZURE_13 # Ensure App Service Authentication is set on Azure App Service
  - CKV_AZURE_137 # ACR admin.
  - CKV_AZURE_139 # Disable public networking for ACR.
  - CKV_AZURE_16 # Ensure that Register with Azure Active Directory is enabled on App Service
  - CKV_AZURE_164 # Signed/trusted images in ACR.
  - CKV_AZURE_165 # Geo-replicated container registries.
  - CKV_AZURE_166 # Image quarantine/verification in ACR.
  - CKV_AZURE_167 # Retention policy for untagged manifests.
  - CKV_AZURE_189 # Disable public network access for Key Vault.
  - CKV_AZURE_212 # Minimum number of instances for failover.
  - CKV_AZURE_222 # Disable public network access for Web App.
  - CKV_AZURE_225 # Zone redundant App Service Plan.
  - CKV_AZURE_233 # ACR zone redundancy.
  - CKV_AZURE_237 # ACR dedicated data endpoint is disabled.
  - CKV_AZURE_33 # Storage logging for Queue service.
  - CKV_AZURE_40 # Set an expiration date on all keys.
  - CKV_AZURE_59 # Disallow public access on storage accounts.
  - CKV_AZURE_63 # Enable HTTP logging.
  - CKV_AZURE_71 # Managed identity provider for App Services.
  - CKV_AZURE_88 # Ensure that app services use Azure Files
  - CKV2_AZURE_21 # Storage logging.
  - CKV2_AZURE_32 # Key vault with private endpoint.
  - CKV2_AZURE_33 # Storage account with private endpoint.
  - CKV2_AZURE_40 # Shared key access to storage account.
  - CKV2_AZURE_41 # SAS expiration policy: Check not working.
  - CKV_DOCKER_2 # Health check added to Dockerfile.
  - CKV_DOCKER_3 # Ensure that a user for the container has been created.
  - CKV_GCP_102 # Anonymous access of Cloud Run.
  - CKV_GCP_109 # PostgreSQL database log levels are set to ERROR or lower. Check not working.
  - CKV_GCP_110 # pgAudit is enabled for your GCP PostgreSQL database. Check not working.
  - CKV_GCP_46 # Ensure Default Service account is not used at a project level.
  - CKV_GCP_55 # PostgreSQL database 'log_min_messages' flag is set to a valid value. Check not working.
  - CKV_GCP_6 # PostgreSQL database all incoming connections to use SSL. Check not working.
  - CKV_GCP_62 # Log bucket access.
  - CKV_GCP_84 # Artifact Registry Repositories are encrypted with Customer Supplied Encryption Keys (CSEK).
skip-path:
  - venv
